### ISSUE TITLE
Seed Value Problem

### ISSUE THREAD

**Issue by AyYildizPilot** [codebox/mazes#2]
Hello,

I don't understand exactly what "Seed Value" is and what it does, or that feature doesn't work.

I tried Ubuntu Local host, it didn't work, I tried it on your demo page and it didn't work.

Seed value is what I understand: to continue with that design after entering the seed number in order not to mask in the next days (I hope I understood it correctly).

Example for a 10x10 square maze on your demo page; "create mask" I did a quick mask, noted the seed number.

I closed the page and opened it again, without changing any settings, I wrote the Seed number, I made a new maze, no it doesn't work, a default 10x10 square maze is formed.

**Comment by codebox** [comment]
The seed value has nothing to do with the mask, it is only used for maze generation. If you use the same seed and same maze parameters (shape, size etc) you should always get the same maze.

**Comment by AyYildizPilot** [comment]
Thank you for the answer,
That feature is unnecessary for this job, why need the same maze parameters, it's better to be unique.
I don't know JS coding, I have very little PHP knowledge.
I looked through some codes and failed. What should I edit to save the created mask to the locale?

**Comment by codebox** [comment]
The seed value is useful if you want to share a maze with someone else or recreate the same maze to work on later. 

Changing the code to save masks is quite a complex job and there is no single place you can make a change to do this, it would involve multiple changes to the code - if you don't have any JS experience it will be difficult.

**Comment by AyYildizPilot** [comment]
It's not something I can correct without my knowledge of JS. I saw a youtube video, someone else edited it for himself.

I thought that if a small code was added to the "Save Mask" command for the masking created in the current structure, it would save that layout as html or save the current settings to cookies, I think, and save locally instead.

I created a heart pixel pattern yesterday after a long struggle, the computer was locked due to a charging problem and all the effort was wasted.

Another issue, the mouse kllick one by one is very difficult in the "create mask" process. Can you add the feature to select many areas while the mouse button is pressed?

and this work is very nice thank you.
